# Generated by Django 5.0.7 on 2024-09-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_issue_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
    ]
