# Generated by Django 5.0.7 on 2024-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_contributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
