# Generated by Django 5.0.7 on 2024-09-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_updated_time_issue_updated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_time',
        ),
    ]
